export const API_URL = process.env.NEXT_PUBLIC_API_URL;
export const QUICKSIGN_CLIENTID = process.env.NEXT_PUBLIC_QUICKSIGN_CLIENTID;
export const QUICKSIGN_CLIENTSECRET =
  process.env.NEXT_PUBLIC_QUICKSIGN_CLIENTSECRET;
export const QUICKSIGN_URL = process.env.NEXT_PUBLIC_QUICKSIGN_URL;
export const QUICKSIGN_DEVELOPER_URL =
  process.env.NEXT_PUBLIC_QUICKSIGN_DEVELOPER_URL;
